import { Component, OnInit } from '@angular/core';
import { AuthService } from '../../services/auth.service';
import { Entity } from '../../models/entity';
import { Event } from '../../models/event';

import { ProfileService } from '../../services/profile.service';

@Component({
  // tslint:disable-next-line:component-selector
  selector: '', // Generated by app.routes.ts
  templateUrl: './app-welcome.component.html',
  styleUrls: ['./app-welcome.component.css']
})
export class AppWelcomeComponent implements OnInit {

title: string;
events: Event[] = [];
entity: Entity;

  constructor( public auth: AuthService,
               private profileService: ProfileService) {
    this.title = 'iVot';
}

  ngOnInit() {
  }

  login() {
    this.auth.login();
  }

}
