import { Component, OnInit } from '@angular/core';
import { AuthService } from '../../services/auth.service';
import { Entity } from '../../models/entity';
import { Event } from '../../models/event';

@Component({
  // tslint:disable-next-line:component-selector
  selector: '', // Generated by app.routes.ts
  templateUrl: './app-welcome.component.html',
  styleUrls: ['./app-welcome.component.css']
})
export class AppWelcomeComponent implements OnInit {

title: string;
events: Event[] = [];
entity: Entity;

  constructor( public auth: AuthService) {
    this.title = 'iVot';
}

  ngOnInit() {
    this.entity = new Entity("Ciberanium","Roc Boronat","Ciberanium@bcnactiva.com",
                             "assets/image.png", "Evento Ciberanium", "12345", this.events);
    console.log(this.entity)
  }

  login() {
    this.auth.login();
  }

}
